# Use the official Composer image as the base image
FROM composer:2.1.14

# Set the working directory
WORKDIR /app

# Copy the entrypoint script


RUN install-php-extensions intl calendar
# Switch to nobody user
COPY updateScript.sh /usr/local/bin/entrypoint.sh
# Make the entrypoint script executable
RUN chmod +x /usr/local/bin/entrypoint.sh
RUN chown nobody:nobody /app
USER nobody
# Command to keep the container running
CMD ["/usr/local/bin/entrypoint.sh"]
